import { v4 as uuidv4 } from 'uuid';
import { BusinessDiscoveryProvider, SearchParams } from './BusinessDiscoveryProvider.js';
import { BusinessLeadCandidate } from '../types/index.js';

const MOCK_BUSINESSES: Omit<BusinessLeadCandidate, 'source'>[] = [
  {
    externalId: 'mock-001',
    name: "Priya's Bake House",
    category: 'Bakery',
    address: '14, Gandhi Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3624,
    longitude: 77.9695,
    phone: '+91-98001-11001',
    website: 'https://example-bakery.com',
    rating: 4.3,
    reviewCount: 142,
    mapsUrl: 'https://maps.google.com/?q=priya+bake+house+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-002',
    name: 'Glamour Touch Salon',
    category: 'Salon',
    address: '7, Anna Nagar',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3654,
    longitude: 77.9710,
    phone: '+91-98001-11002',
    website: undefined,
    rating: 4.1,
    reviewCount: 87,
    mapsUrl: 'https://maps.google.com/?q=glamour+touch+salon+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-003',
    name: 'FitLife Gym',
    category: 'Gym',
    address: '22, Main Street',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3601,
    longitude: 77.9688,
    phone: '+91-98001-11003',
    website: 'https://fitlifegym-demo.com',
    rating: 4.5,
    reviewCount: 230,
    mapsUrl: 'https://maps.google.com/?q=fitlife+gym+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-004',
    name: 'Royal Biryani House',
    category: 'Restaurant',
    address: '3, Market Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3630,
    longitude: 77.9700,
    phone: '+91-98001-11004',
    website: undefined,
    rating: 4.7,
    reviewCount: 512,
    mapsUrl: 'https://maps.google.com/?q=royal+biryani+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-005',
    name: 'Bright Minds Tuition Centre',
    category: 'Tuition Centre',
    address: '56, School Lane',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3645,
    longitude: 77.9721,
    phone: '+91-98001-11005',
    website: 'https://brightminds-demo.com',
    rating: 4.2,
    reviewCount: 63,
    mapsUrl: 'https://maps.google.com/?q=bright+minds+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-006',
    name: 'Mobile World',
    category: 'Mobile Shop',
    address: '9, Electronics Complex',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3618,
    longitude: 77.9715,
    phone: '+91-98001-11006',
    website: undefined,
    rating: 3.9,
    reviewCount: 45,
    mapsUrl: 'https://maps.google.com/?q=mobile+world+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-007',
    name: 'Dream Homes Real Estate',
    category: 'Real Estate',
    address: '1, Tower Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3608,
    longitude: 77.9693,
    phone: '+91-98001-11007',
    website: 'https://dreamhomes-demo.com',
    rating: 4.0,
    reviewCount: 29,
    mapsUrl: 'https://maps.google.com/?q=dream+homes+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-008',
    name: "Anbu's Sweet Shop",
    category: 'Bakery',
    address: '18, Bus Stand Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3635,
    longitude: 77.9704,
    phone: '+91-98001-11008',
    website: undefined,
    rating: 4.6,
    reviewCount: 198,
    mapsUrl: 'https://maps.google.com/?q=anbu+sweet+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-009',
    name: 'Style Zone Unisex Salon',
    category: 'Salon',
    address: '33, Central Avenue',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3650,
    longitude: 77.9698,
    phone: '+91-98001-11009',
    website: 'https://stylezone-demo.com',
    rating: 4.4,
    reviewCount: 154,
    mapsUrl: 'https://maps.google.com/?q=style+zone+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-010',
    name: 'Power Fitness Studio',
    category: 'Gym',
    address: '77, New Layout',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3625,
    longitude: 77.9685,
    phone: undefined,
    website: undefined,
    rating: 3.8,
    reviewCount: 22,
    mapsUrl: 'https://maps.google.com/?q=power+fitness+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-011',
    name: 'Spice Garden Family Restaurant',
    category: 'Restaurant',
    address: '44, Collector Office Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3640,
    longitude: 77.9720,
    phone: '+91-98001-11011',
    website: 'https://spicegarden-demo.com',
    rating: 4.1,
    reviewCount: 311,
    mapsUrl: 'https://maps.google.com/?q=spice+garden+dindigul',
    openingStatus: 'Closed',
  },
  {
    externalId: 'mock-012',
    name: 'Scholars Academy',
    category: 'Tuition Centre',
    address: '11, Temple Street',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3660,
    longitude: 77.9710,
    phone: '+91-98001-11012',
    website: undefined,
    rating: 4.3,
    reviewCount: 78,
    mapsUrl: 'https://maps.google.com/?q=scholars+academy+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-013',
    name: 'Tech Hub Mobile Repairs',
    category: 'Mobile Shop',
    address: '5, Electronics Market',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3612,
    longitude: 77.9708,
    phone: '+91-98001-11013',
    website: 'https://techhub-demo.com',
    rating: 4.0,
    reviewCount: 91,
    mapsUrl: 'https://maps.google.com/?q=tech+hub+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-014',
    name: 'Green Valley Properties',
    category: 'Real Estate',
    address: '2, Housing Board',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3622,
    longitude: 77.9718,
    phone: '+91-98001-11014',
    website: undefined,
    rating: 3.7,
    reviewCount: 16,
    mapsUrl: 'https://maps.google.com/?q=green+valley+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-015',
    name: 'Golden Sweets & Bakery',
    category: 'Bakery',
    address: '28, Railway Station Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3638,
    longitude: 77.9695,
    phone: '+91-98001-11015',
    website: 'https://goldensweets-demo.com',
    rating: 4.5,
    reviewCount: 267,
    mapsUrl: 'https://maps.google.com/?q=golden+sweets+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-016',
    name: "Trendy Nails & Beauty",
    category: 'Salon',
    address: '66, Women\'s College Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3656,
    longitude: 77.9705,
    phone: '+91-98001-11016',
    website: undefined,
    rating: 4.6,
    reviewCount: 203,
    mapsUrl: 'https://maps.google.com/?q=trendy+nails+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-017',
    name: 'Iron & Steel Fitness',
    category: 'Gym',
    address: '12, Industrial Area',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3598,
    longitude: 77.9700,
    phone: '+91-98001-11017',
    website: 'https://ironsteel-demo.com',
    rating: 4.2,
    reviewCount: 112,
    mapsUrl: 'https://maps.google.com/?q=iron+steel+fitness+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-018',
    name: 'Chettinad Kitchen',
    category: 'Restaurant',
    address: '99, Heritage Street',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3648,
    longitude: 77.9715,
    phone: '+91-98001-11018',
    website: undefined,
    rating: 4.8,
    reviewCount: 422,
    mapsUrl: 'https://maps.google.com/?q=chettinad+kitchen+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-019',
    name: 'Success Point Coaching',
    category: 'Tuition Centre',
    address: '41, Government School Road',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3665,
    longitude: 77.9695,
    phone: '+91-98001-11019',
    website: 'https://successpoint-demo.com',
    rating: 4.4,
    reviewCount: 55,
    mapsUrl: 'https://maps.google.com/?q=success+point+dindigul',
    openingStatus: 'Open',
  },
  {
    externalId: 'mock-020',
    name: 'Vivo & Samsung Hub',
    category: 'Mobile Shop',
    address: '3, South Car Street',
    city: 'Dindigul',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 10.3610,
    longitude: 77.9712,
    phone: '+91-98001-11020',
    website: 'https://vivosamsunghub-demo.com',
    rating: 4.0,
    reviewCount: 67,
    mapsUrl: 'https://maps.google.com/?q=vivo+samsung+dindigul',
    openingStatus: 'Open',
  },
];

export class MockBusinessDiscoveryProvider implements BusinessDiscoveryProvider {
  readonly providerName = 'mock';

  async searchBusinesses(params: SearchParams): Promise<BusinessLeadCandidate[]> {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 1500));

    let results = MOCK_BUSINESSES.map((b) => ({
      ...b,
      source: 'mock',
      // Override city/state/country from search params
      city: params.city || b.city,
      state: params.state || b.state,
      country: params.country || b.country,
    }));

    // Filter by category if specified (fuzzy match)
    if (params.category && params.category.toLowerCase() !== 'all') {
      results = results.filter((b) =>
        b.category.toLowerCase().includes(params.category.toLowerCase()) ||
        params.category.toLowerCase().includes(b.category.toLowerCase())
      );
      // If no exact match, return a subset of all mock data
      if (results.length === 0) {
        results = MOCK_BUSINESSES.slice(0, Math.min(params.limit, 10)).map((b) => ({
          ...b,
          source: 'mock',
          category: params.category,
          city: params.city || b.city,
          state: params.state || b.state,
          country: params.country || b.country,
          externalId: `mock-custom-${uuidv4().slice(0, 8)}`,
        }));
      }
    }

    // Apply filters
    if (params.filters) {
      const f = params.filters;
      if (f.minRating) results = results.filter((b) => (b.rating ?? 0) >= f.minRating!);
      if (f.minReviews) results = results.filter((b) => (b.reviewCount ?? 0) >= f.minReviews!);
      if (f.hasPhone) results = results.filter((b) => !!b.phone);
      if (f.hasWebsite) results = results.filter((b) => !!b.website);
      if (f.onlyOpen) results = results.filter((b) => b.openingStatus === 'Open');
    }

    return results.slice(0, params.limit);
  }
}
